import type { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
    await knex('districts').del(); 

    await knex('districts').insert([
        {  name: 'Ablekuma Central', code: 'G7', regionid: 7 },
        {  name: 'Ablekuma North', code: 'GF', regionid: 7 },
        {  name: 'Ablekuma West', code: 'GU', regionid: 7 },
        { name: 'Abuakwa North', code: 'E4', regionid: 6 },
        { name: 'Abuakwa South', code: 'E5', regionid: 6 },
        { name: 'Abura Asebu Kwamankese', code: 'CA', regionid: 5 },
        {  name: 'Accra', code: 'GA', regionid: 7 },
        { name: 'Achiase', code: 'EC', regionid: 6 },
        {  name: 'Ada East', code: 'GY', regionid: 7 },
        {  name: 'Ada West', code: 'GX', regionid: 7 },
        {  name: 'Adaklu', code: 'VA', regionid: 14 },
        { name: 'Adansi Asokwa', code: 'A5', regionid: 1 },
        { name: 'Adansi North', code: 'A2', regionid: 1 },
        { name: 'Adansi South', code: 'A3', regionid: 1 },
        {  name: 'Adentan', code: 'GD', regionid: 7 },
        {  name: 'Afadjato South', code: 'VF', regionid: 14 },
        { name: 'Afigya Kwabre', code: 'AF', regionid: 1 },
        { name: 'Afigya Kwabre North', code: 'AAK', regionid: 1 },
        { name: 'Agona East', code: 'CP', regionid: 5 },
        { name: 'Agona West', code: 'CO', regionid: 5 },
        {  name: 'Agotime Ziope', code: 'VG', regionid: 14 },
        { name: 'Ahafo Ano North', code: 'AX', regionid: 1 },
        { name: 'Ahafo Ano South East', code: 'A8', regionid: 1 },
        { name: 'Ahafo Ano South West', code: 'AY', regionid: 1 },
        {  name: 'Ahanta West', code: 'WH', regionid: 15 },
        { name: 'Ajumako Enyan Esiam', code: 'CJ', regionid: 5 },
        {  name: 'Akatsi North', code: 'VW', regionid: 14 },
        {  name: 'Akatsi South', code: 'VX', regionid: 14 },
        { name: 'Akrofuom', code: 'AAF', regionid: 1 },
        { name: 'Akuapem North', code: 'E2', regionid: 6 },
        { name: 'Akuapem South', code: 'E3', regionid: 6 },
        { name: 'Akyemansa', code: 'EM', regionid: 6 },
        { name: 'Amansie Central', code: 'AV', regionid: 1 },
        { name: 'Amansie South', code: 'AAM', regionid: 1 },
        { name: 'Amansie West', code: 'AW', regionid: 1 },
        {  name: 'Anloga', code: 'VN', regionid: 14 },
        {  name: 'Aowin', code: 'YA', regionid: 16 },
        { name: 'Asante Akim Central', code: 'AC', regionid: 1 },
        { name: 'Asante Akim North', code: 'AN', regionid: 1 },
        { name: 'Asante Akim South', code: 'AA', regionid: 1 },
        {  name: 'Asene Manso Akroso', code: 'E8', regionid: 6 },
        {  name: 'Ashaiman', code: 'GB', regionid: 7 },
        { name: 'Asikuma / Odoben / Brakwa', code: 'CB', regionid: 5 },
        { name: 'Asokore Mampong', code: 'AS', regionid: 1 },
        { name: 'Asokwa', code: 'AAS', regionid: 1 },
        { name: 'Assin Central', code: 'CN', regionid: 5 },
        { name: 'Assin North', code: 'CR', regionid: 5 },
        { name: 'Assin South', code: 'CS', regionid: 5 },
        { name: 'Asunafo North', code: 'HA', regionid: 3 },
        { name: 'Asunafo South', code: 'HB', regionid: 3 },
        {  name: 'Asuogyaman', code: 'EA', regionid: 6 },
        { name: 'Asutifi North', code: 'HQ', regionid: 3 },
        { name: 'Asutifi South', code: 'HR', regionid: 3 },
        { name: 'Atebubu-Amantin', code: 'TA', regionid: 4 },
        {  name: 'Atiwa East', code: 'E9', regionid: 6 },
        {  name: 'Atiwa West', code: 'ET', regionid: 6 },
        { name: 'Atwima Kwanwoma', code: 'AG', regionid: 1 },
        { name: 'Atwima Mponua', code: 'AI', regionid: 1 },
        { name: 'Atwima Nwabiagya', code: 'AH', regionid: 1 },
        { name: 'Atwima Nwabiagya North', code: 'AAT', regionid: 1 },
        { name: 'Awutu Senya East', code: 'CX', regionid: 5 },
        {  name: 'Ayawaso Central', code: 'G2', regionid: 7 },
        {  name: 'Ayawaso East', code: 'GV', regionid: 7 },
        {  name: 'Ayawaso North', code: 'G3', regionid: 7 },
        {  name: 'Ayawaso West', code: 'G4', regionid: 7 },
        {  name: 'Ayensuano', code: 'EO', regionid: 6 },
        { name: 'Banda', code: 'BA', regionid: 2 },
        {  name: 'Bawku', code: 'UA', regionid: 12 },
        {  name: 'Bawku West', code: 'UW', regionid: 12 },
        { name: 'Bekwai', code: 'AB', regionid: 1 },
        { name: 'Berekum East', code: 'BB', regionid: 2 },
        { name: 'Berekum West', code: 'BC', regionid: 2 },
        {  name: 'Bia East', code: 'YE', regionid: 16 },
        {  name: 'Bia West', code: 'YW', regionid: 16 },
        {  name: 'Biakoye', code: 'OB', regionid: 10 },
        {  name: 'Bibiani Anhwiaso Bekwai', code: 'YB', regionid: 16 },
        {  name: 'Binduri', code: 'UU', regionid: 12 },
        {  name: 'Birim Central', code: 'EB', regionid: 6 },
        {  name: 'Birim North', code: 'EX', regionid: 6 },
        {  name: 'Birim South', code: 'EZ', regionid: 6 },
        {  name: 'Bodi', code: 'YD', regionid: 16 },
        {  name: 'Bole', code: 'SB', regionid: 11 },
        {  name: 'Bolgatanga', code: 'UB', regionid: 12 },
        {  name: 'Bolgatanga East', code: 'UE', regionid: 12 },
        {  name: 'Bongo', code: 'UO', regionid: 12 },
        { name: 'Bosome Freho', code: 'A4', regionid: 1 },
        { name: 'Bosomtwe', code: 'AT', regionid: 1 },
        {  name: 'Builsa North', code: 'UR', regionid: 12 },
        {  name: 'Builsa South', code: 'US', regionid: 12 },
        {  name: 'Bunkpurugu Nakpanduri', code: 'MP', regionid: 8 },
        { name: 'Cape Coast', code: 'CC', regionid: 5 },
        {  name: 'Central Gonja', code: 'SG', regionid: 11 },
        {  name: 'Central Tongu', code: 'VV', regionid: 14 },
        {  name: 'Chereponi', code: 'MC', regionid: 8 },
        {  name: 'Daffiama Bussie Issa', code: 'XD', regionid: 13 },
        {  name: 'Denkyembour', code: 'ED', regionid: 6 },
        { name: 'Dormaa Central', code: 'BD', regionid: 2 },
        { name: 'Dormaa East', code: 'BE', regionid: 2 },
        { name: 'Dormaa West', code: 'BF', regionid: 2 },
        {  name: 'East Gonja', code: 'SE', regionid: 11 },
        {  name: 'East Mamprusi', code: 'ME', regionid: 8 },
        {  name: 'Effia Kwesimintim', code: 'WK', regionid: 15 },
        { name: 'Effutu', code: 'CE', regionid: 5 },
        { name: 'Ejisu', code: 'AE', regionid: 1 },
        { name: 'Ejura-Sekyedumase', code: 'AJ', regionid: 1 },
        { name: 'Ekumfi', code: 'CF', regionid: 5 },
        {  name: 'Ellembelle', code: 'WE', regionid: 15 },
        {  name: 'Fanteakwa North', code: 'EF', regionid: 6 },
        {  name: 'Fanteakwa South', code: 'E6', regionid: 6 },
        {  name: 'Ga Central', code: 'GC', regionid: 7 },
        {  name: 'Ga East', code: 'GE', regionid: 7 },
        {  name: 'Ga North', code: 'GG', regionid: 7 },
        {  name: 'Ga South', code: 'GS', regionid: 7 },
        {  name: 'Ga West', code: 'GW', regionid: 7 },
        {  name: 'Garu', code: 'UG', regionid: 12 },
        { name: 'Gomoa Central', code: 'CL', regionid: 5 },
        { name: 'Gomoa East', code: 'CG', regionid: 5 },
        { name: 'Gomoa West', code: 'CI', regionid: 5 },
        {  name: 'Guan', code: 'OG', regionid: 10 },
        {  name: 'Gushiegu', code: 'NG', regionid: 9 },
        { name: 'Hemang Lower Denkyira', code: 'CH', regionid: 5 },
        {  name: 'Ho', code: 'VH', regionid: 14 },
        {  name: 'Ho West', code: 'VI', regionid: 14 },
        {  name: 'Hohoe', code: 'VC', regionid: 14 },
        { name: 'Jaman North', code: 'BJ', regionid: 2 },
        { name: 'Jaman South', code: 'BI', regionid: 2 },
        {  name: 'Jasikan', code: 'OJ', regionid: 10 },
        {  name: 'Jirapa', code: 'XJ', regionid: 13 },
        {  name: 'Jomoro', code: 'WJ', regionid: 15 },
        { name: 'Juaben', code: 'AL', regionid: 1 },
        {  name: 'Juaboso', code: 'YJ', regionid: 16 },
        {  name: 'Kadjebi', code: 'OK', regionid: 10 },
        {  name: 'Karaga', code: 'NR', regionid: 9 },
        {  name: 'Kassena Nankana East', code: 'UK', regionid: 12 },
        {  name: 'Kassena Nankana West', code: 'UL', regionid: 12 },
        {  name: 'Keta', code: 'VK', regionid: 14 },
        {  name: 'Ketu North', code: 'VY', regionid: 14 },
        {  name: 'Ketu South', code: 'VZ', regionid: 14 },
        { name: 'Kintampo North', code: 'TK', regionid: 4 },
        { name: 'Kintampo South', code: 'TL', regionid: 4 },
        { name: 'Komenda Edina Eguafo', code: 'CK', regionid: 5 },
        {  name: 'Korle Klottey', code: 'GR', regionid: 7 },
        {  name: 'Kpandai', code: 'NA', regionid: 9 },
        {  name: 'Kpando', code: 'VP', regionid: 14 },
        {  name: 'Kpone Katamanso', code: 'GK', regionid: 7 },
        {  name: 'Krachi East', code: 'OE', regionid: 10 },
        {  name: 'Krachi Nchumuru', code: 'OQ', regionid: 10 },
        {  name: 'Krachi West', code: 'OW', regionid: 10 },
        {  name: 'Krowor', code: 'G6', regionid: 7 },
        { name: 'Kumasi', code: 'AK', regionid: 1 },
        {  name: 'Kumbungu', code: 'NK', regionid: 9 },
        { name: 'Kwabre East', code: 'AD', regionid: 1 },
        { name: 'Kwadaso', code: 'AKW', regionid: 1 },
        {  name: 'Kwaebibirem', code: 'EK', regionid: 6 },
        {  name: 'Kwahu Afram Plains North', code: 'EP', regionid: 6 },
        {  name: 'Kwahu Afram Plains South', code: 'EQ', regionid: 6 },
        {  name: 'Kwahu East', code: 'EH', regionid: 6 },
        {  name: 'Kwahu South', code: 'EI', regionid: 6 },
        {  name: 'Kwahu West', code: 'EJ', regionid: 6 },
        {  name: 'La Dade Kotopon', code: 'GL', regionid: 7 },
        {  name: 'La Nkwantanang Madina', code: 'GM', regionid: 7 },
        {  name: 'Lambussie Karni', code: 'XK', regionid: 13 },
        {  name: 'Lawra', code: 'XL', regionid: 13 },
        {  name: 'Ledzokuku', code: 'GZ', regionid: 7 },
        {  name: 'Lower Manya Krobo', code: 'EL', regionid: 6 },
        { name: 'Mampong', code: 'AM', regionid: 1 },
        {  name: 'Mamprugu Moaduri', code: 'MM', regionid: 8 },
        { name: 'Mfantseman', code: 'CM', regionid: 5 },
        {  name: 'Mion', code: 'NI', regionid: 9 },
        {  name: 'Mpohor', code: 'WM', regionid: 15 },
        {  name: 'Nabdam', code: 'UN', regionid: 12 },
        {  name: 'Nadowli Kaleo', code: 'XO', regionid: 13 },
        {  name: 'Nandom', code: 'XN', regionid: 13 },
        {  name: 'Nanton', code: 'NU', regionid: 9 },
        {  name: 'Nanumba North', code: 'NN', regionid: 9 },
        {  name: 'Nanumba South', code: 'NO', regionid: 9 },
        {  name: 'New Juaben North', code: 'E7', regionid: 6 },
        {  name: 'New Juaben South', code: 'EN', regionid: 6 },
        {  name: 'Ningo Prampram', code: 'GN', regionid: 7 },
        { name: 'Nkoranza North', code: 'TN', regionid: 4 },
        { name: 'Nkoranza South', code: 'TO', regionid: 4 },
        {  name: 'Nkwanta North', code: 'ON', regionid: 10 },
        {  name: 'Nkwanta South', code: 'OS', regionid: 10 },
        {  name: 'North Dayi', code: 'VD', regionid: 14 },
        {  name: 'North East Gonja', code: 'SJ', regionid: 11 },
        {  name: 'North Gonja', code: 'SN', regionid: 11 },
        {  name: 'North Tongu', code: 'VT', regionid: 14 },
        {  name: 'Nsawam Adoagyiri', code: 'EG', regionid: 6 },
        {  name: 'Nzema East', code: 'WN', regionid: 15 },
        { name: 'Obuasi', code: 'AO', regionid: 1 },
        { name: 'Obuasi East', code: 'AOE', regionid: 1 },
        { name: 'Offinso North', code: 'A6', regionid: 1 },
        { name: 'Offinso South', code: 'A7', regionid: 1 },
        { name: 'Oforikrom', code: 'AOK', regionid: 1 },
        {  name: 'Okaikwei North', code: 'GI', regionid: 7 },
        {  name: 'Okere', code: 'ER', regionid: 6 },
        { name: 'Old Tafo', code: 'AOT', regionid: 1 },
        {  name: 'Prestea Huni Valley', code: 'WP', regionid: 15 },
        { name: 'Pru East', code: 'TP', regionid: 4 },
        { name: 'Pru West', code: 'TW', regionid: 4 },
        {  name: 'Pusiga', code: 'UP', regionid: 12 },
        {  name: 'Saboba', code: 'NX', regionid: 9 },
        {  name: 'Sagnerigu', code: 'NS', regionid: 9 },
        {  name: 'Savelugu', code: 'NV', regionid: 9 },
        {  name: 'Sawla Tuna Kalba', code: 'SS', regionid: 11 },
        {  name: 'Sefwi Akontombra', code: 'YK', regionid: 16 },
        {  name: 'Sefwi Wiawso', code: 'YS', regionid: 16 },
        {  name: 'Sekondi-Takoradi', code: 'WS', regionid: 15 },
        { name: 'Sekyere Afram Plains', code: 'AP', regionid: 1 },
        { name: 'Sekyere Central', code: 'AQ', regionid: 1 },
        { name: 'Sekyere East', code: 'AR', regionid: 1 },
        { name: 'Sekyere Kumawu', code: 'AU', regionid: 1 },
        { name: 'Sekyere South', code: 'AZ', regionid: 1 },
        { name: 'Sene East', code: 'TE', regionid: 4 },
        { name: 'Sene West', code: 'TS', regionid: 4 },
        {  name: 'Shai-Osudoku', code: 'GO', regionid: 7 },
        {  name: 'Shama', code: 'WR', regionid: 15 },
        {  name: 'Sissala East', code: 'XS', regionid: 13 },
        {  name: 'Sissala West', code: 'XT', regionid: 13 },
        {  name: 'South Dayi', code: 'VE', regionid: 14 },
        {  name: 'South Tongu', code: 'VU', regionid: 14 },
        {  name: 'Suaman', code: 'YU', regionid: 16 },
        { name: 'Suame', code: 'ASU', regionid: 1 },
        {  name: 'Suhum', code: 'ES', regionid: 6 },
        { name: 'Sunyani', code: 'BS', regionid: 2 },
        { name: 'Sunyani West', code: 'BY', regionid: 2 },
        { name: 'Tain', code: 'BZ', regionid: 2 },
        {  name: 'Talensi', code: 'UT', regionid: 12 },
        {  name: 'Tamale', code: 'NT', regionid: 9 },
        { name: 'Tano North', code: 'HT', regionid: 3 },
        { name: 'Tano South', code: 'HT', regionid: 3 },
        {  name: 'Tarkwa Nsuaem', code: 'WT', regionid: 15 },
        {  name: 'Tatale Sangule', code: 'NF', regionid: 9 },
        { name: 'Techiman', code: 'TT', regionid: 4 },
        { name: 'Techiman North', code: 'TT', regionid: 4 },
        {  name: 'Tema', code: 'GT', regionid: 7 },
        {  name: 'Tema West', code: 'GQ', regionid: 7 },
        {  name: 'Tempane', code: 'UM', regionid: 12 },
        {  name: 'Tolon', code: 'NL', regionid: 9 },
        { name: 'Twifo Ati-Morkwa', code: 'CT', regionid: 5 },
        { name: 'Upper Denkyira East', code: 'CU', regionid: 5 },
        { name: 'Upper Denkyira West', code: 'CV', regionid: 5 },
        {  name: 'Upper Manya Krobo', code: 'EU', regionid: 6 },
        {  name: 'Upper West Akim', code: 'EV', regionid: 6 },
        {  name: 'Wa', code: 'XW', regionid: 13 },
        {  name: 'Wa East', code: 'XX', regionid: 13 },
        {  name: 'Wa West', code: 'XY', regionid: 13 },
        {  name: 'Wassa Amenfi Central', code: 'WW', regionid: 15 },
        {  name: 'Wassa Amenfi East', code: 'WX', regionid: 15 },
        {  name: 'Wassa Amenfi West', code: 'WY', regionid: 15 },
        {  name: 'Wassa East', code: 'WZ', regionid: 15 },
        {  name: 'Weija Gbawe', code: 'GJ', regionid: 7 },
        { name: 'Wenchi', code: 'BW', regionid: 2 },
        {  name: 'West Akim', code: 'EW', regionid: 6 },
        {  name: 'West Gonja', code: 'SW', regionid: 11 },
        {  name: 'West Mamprusi', code: 'MW', regionid: 8 },
        {  name: 'Yendi', code: 'NY', regionid: 9 },
        {  name: 'Yilo Krobo', code: 'EY', regionid: 6 },
        {  name: 'Yunyoo Nasuan', code: 'MY', regionid: 8 },
        {  name: 'Zabzugu', code: 'NZ', regionid: 9 },
    ]);
}